import { test } from '@playwright/test';

/**
 * Skips a test if the given MongoDB config variable is not implemented
 * in the B2B frontend codebase (YOMCL/b2b).
 *
 * Call at the top of any test that validates a specific config variable:
 *
 *   test('confirmCartText — botón personalizado', async ({ page }) => {
 *     skipIfNotInB2B(CLIENT, 'confirmCartText');
 *     // rest of test...
 *   });
 *
 * The notImplementedInB2B list is generated by:
 *   python3 tools/b2b-feature-validator.py
 *   python3 tools/sync-clients.py
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function skipIfNotInB2B(client: any, varName: string): void {
  const notImpl = client.notImplementedInB2B || [];
  if (notImpl.includes(varName)) {
    test.skip(true, `${varName} no implementado en B2B frontend — pendiente de desarrollo`);
  }
}
