/**
 * AUTO-GENERATED by tools/sync-clients.py
 * Source: data/qa-matrix.json
 * Last sync: 2026-04-01T11:30:00Z
 *
 * DO NOT EDIT MANUALLY
 * To regenerate: python3 tools/sync-clients.py
 *
 * Flow:
 *   1. python3 data/mongo-extractor.py   # MongoDB → qa-matrix.json
 *   2. python3 tools/sync-clients.py     # qa-matrix.json → this file
 */

import { test as base, expect } from '@playwright/test';

function creds(prefix: string) {
  return {
    email: process.env[`${prefix}_EMAIL`] || '',
    password: process.env[`${prefix}_PASSWORD`] || '',
  };
}

interface ClientConfig {
  name: string;
  baseURL: string;
  loginPath: string;
  credentials: { email: string; password: string };
  config: Record<string, any>;
  coupons?: Array<{ code: string; discount: any }>; // From yom-promotions
  banners?: Array<{ title: string; position: string }>; // From b2b-marketing
}

const clients: Record<string, ClientConfig> = {
  codelpa: {
    name: "Codelpa",
    baseURL: "https://beta-codelpa.solopide.me",
    loginPath: "/login",
    credentials: creds("CODELPA"),
    coupons: [
    { code: "PROMO10", discount: {"type": "percentage", "value": 10} },     { code: "WELCOME5", discount: {"type": "percentage", "value": 5} }
  ],
    banners: [
    { title: "Oferta especial productos B2B", position: "hero" },     { title: "Envío gratis compras >100k", position: "top" }
  ],
    // Conditional tests: C1-A1, C2-E1, C3-E2
    config: {
      anonymousAccess: false,
      anonymousHideCart: true,
      anonymousHidePrice: true,
      disableCart: false,
      disableCommerceEdit: true,
      editAddress: false,
      enableCoupons: true,
      enableMassiveOrderSend: true,
      enableOrderApproval: true,
      enableSellerDiscount: true,
      enableTask: true,
      hasAllDistributionCenters: true,
      hasStockEnabled: true,
      hideReceiptType: true,
      "hooks.shippingHook": true,
      "hooks.stockHook": true,
      pendingDocuments: true,
      purchaseOrderEnabled: true,
      "synchronization.enableSyncImages": true,
      useMongoPricing: true,
    },
  },
  surtiventas: {
    name: "Surtiventas",
    baseURL: "https://surtiventas.solopide.me",
    loginPath: "/auth/jwt/login",
    credentials: creds("SURTIVENTAS"),
    coupons: [
    { code: "SURTI15", discount: {"type": "percentage", "value": 15} }
  ],
    banners: [
    { title: "Catálogo actualizado abril", position: "hero" }
  ],
    // Conditional tests: C1-A1, C2-E6
    config: {
      anonymousAccess: false,
      anonymousHideCart: true,
      anonymousHidePrice: false,
      "commerce.enableCreateCommerce": true,
      disableCart: false,
      disableCommerceEdit: false,
      editAddress: true,
      enableChooseSaleUnit: true,
      enableCoupons: true,
      enableMassiveOrderSend: true,
      enableOrderApproval: false,
      enableSellerDiscount: true,
      hasMultiUnitEnabled: true,
      hasNoSaleFilter: true,
      hasSingleDistributionCenter: true,
      hasStockEnabled: true,
      hideReceiptType: false,
      limitAddingByStock: true,
      "packaging.amountUsesUnits": true,
      pendingDocuments: false,
      "taxes.useTaxRate": true,
      useMongoPricing: false,
      useNewPromotions: true,
    },
  },
};

export default clients;
