/**
 * AUTO-GENERATED by tools/sync-clients.py
 * Source: data/qa-matrix.json
 * Last sync: 2026-04-02T13:58:02.371218+00:00
 *
 * DO NOT EDIT MANUALLY
 * To regenerate: python3 tools/sync-clients.py
 *
 * Flow:
 *   1. python3 data/mongo-extractor.py   # MongoDB → qa-matrix.json
 *   2. python3 tools/sync-clients.py     # qa-matrix.json → this file
 */

import { test as base, expect } from '@playwright/test';

function creds(prefix: string) {
  return {
    email: process.env[`${prefix}_EMAIL`] || '',
    password: process.env[`${prefix}_PASSWORD`] || '',
  };
}

interface ClientConfig {
  name: string;
  baseURL: string;
  loginPath: string;
  credentials: { email: string; password: string };
  config: Record<string, any>;
  coupons?: Array<{ code: string; discount: any }>; // From yom-promotions
  banners?: Array<{ title: string; position: string }>; // From b2b-marketing
  promotions?: Array<any>; // From yom-promotions
  integrations?: { segments: any; overrides: any; userSegments: any }; // From integrations cluster
}

const clients: Record<string, ClientConfig> = {
  codelpa: {
    name: "Codelpa",
    baseURL: "https://codelpa.youorder.me",
    loginPath: "/login",
    credentials: creds("CODELPA"),
    coupons: [
    { code: "PROMO10", discount: 10 },     { code: "CODELPA20", discount: 20 },     { code: "DSCTO5K", discount: 5000 }
  ],
    banners: [
    { title: "¡Novedad en Pinturas Codelpa!", position: "hero" },     { title: "Ofertas de Revestimientos", position: "sidebar" }
  ],
    promotions: [{"name": "Descuento Volumen Marzo", "discount": 10, "active": true}, {"name": "Promo Revendedores", "discount": 15, "active": true}],
    integrations: {"segments": [], "overrides": [], "userSegments": []},
    // Conditional tests: C2-E10, C2-E4, C2-E5, C2-E9, C3-E3, C3-E4, C3-E6, C6-E3, P1-12, P2-02, +8 more
    config: {
      anonymousAccess: false,
      anonymousHideCart: true,
      anonymousHidePrice: true,
      "contact.about": "Grupo Codelpa Colores del Pac\u00edfico, es la empresa de pinturas y revestimientos m\u00e1s grande del pa\u00eds, agrupando marcas de pinturas como Ceresita, Sipa, Soquina, Chilcorrof\u00edn, Pinmor y Titanium 2K de Sipa.",
      "contact.branchesContactInformation": [{"address": "Camino Lo Echevers 801, Quilicura", "phone": "+562227262800", "email": "info@codelpa.cl"}],
      "contact.email": "info@codelpa.cl",
      disableCart: false,
      disableCommerceEdit: true,
      disableShowEstimatedDeliveryHour: false,
      editAddress: false,
      enableAskDeliveryDate: false,
      enableCoupons: true,
      enableCreditStateMessage: false,
      enableDialogNoSellReason: false,
      enableInvoicesList: false,
      enableMassiveOrderSend: true,
      enableOrderApproval: true,
      enableOrderValidation: true,
      enableSellerDiscount: true,
      enableTask: true,
      externalAccess: false,
      hasAllDistributionCenters: true,
      hasSingleDistributionCenter: false,
      hasStockEnabled: true,
      hidePrices: false,
      hideReceiptType: true,
      "hooks.cartShoppingHook": false,
      "hooks.getPendingDocumentsHook": false,
      "hooks.shippingHook": true,
      "hooks.stockHook": true,
      "hooks.updateTrafficLightHook": false,
      inMaintenance: false,
      includeTaxRateInPrices: false,
      lazyLoadingPrices: false,
      ordersRequireAuthorization: false,
      ordersRequireVerification: false,
      "packagingInformation.hidePackagingInformationB2B": false,
      "packagingInformation.hideSingleItemPackagingInformationB2B": true,
      "packagingInformation.ignoreUnitOnPackInformationB2B": false,
      "payment.enableNewPaymentModule": false,
      pendingDocuments: true,
      pointsEnabled: false,
      productVariability: "none",
      purchaseOrderEnabled: true,
      "shoppingDetail.lastOrder": true,
      showEmptyCategories: false,
      showMinOne: false,
      "synchronization.enableSyncImages": true,
      "taxes.showSummary": true,
      "taxes.taxRate": 0,
      "taxes.useTaxRate": false,
      useMobileGps: true,
      useMongoPricing: true,
      weightInfo: false,
    },
  },
  surtiventas: {
    name: "Surtiventas",
    baseURL: "https://surtiventas.youorder.me",
    loginPath: "/auth/jwt/login",
    credentials: creds("SURTIVENTAS"),
    coupons: [
    { code: "SURTI15", discount: 15 },     { code: "WELCOME10", discount: 10 },     { code: "BULK3K", discount: 3000 }
  ],
    banners: [
    { title: "Productos Frescos Disponibles", position: "hero" }
  ],
    promotions: [{"name": "Martes de Ofertas", "discount": 20, "active": true}, {"name": "Compra 2 Lleva 3", "discount": 33, "active": true}],
    integrations: {"segments": [], "overrides": [], "userSegments": []},
    // Conditional tests: C2-E2, C2-E5, C2-E6, C3-E6, P2-01, P2-03, P3-01, P3-02, P3-04, P3-05, +3 more
    config: {
      anonymousAccess: false,
      anonymousHideCart: true,
      anonymousHidePrice: false,
      "blockedClientAlert.enableBlockedClientAlert": false,
      businessUnits: [],
      "commerce.enableCreateCommerce": true,
      "contact.about": "Surtiventas opera con el claro prop\u00f3sito de satisfacer las necesidades b\u00e1sicas del comerciante chileno, con un servicio personalizado de venta que se extiende a lo largo y ancho del pa\u00eds.",
      "contact.branchesContactInformation": [{"phone": "+562 2820 6400", "email": "srvcliente1@surtiventas.cl"}],
      "contact.email": "srvcliente1@surtiventas.cl",
      disableCart: false,
      disableCommerceEdit: false,
      disableObservationInput: false,
      disablePayments: false,
      disableShowEstimatedDeliveryHour: false,
      "discountTypes.discountTypesList": [],
      "discountTypes.enableOrderDiscountType": false,
      "discountTypes.enableProductDiscountType": false,
      editAddress: true,
      enableAskDeliveryDate: false,
      enableBetaButtons: false,
      enableChooseSaleUnit: true,
      enableCoupons: true,
      enableCreditNotes: false,
      enableDialogNoSellReason: false,
      enableDistributionCentersSelector: false,
      enableInvoicesList: false,
      enableMassiveOrderSend: true,
      enableNewUI: false,
      enableOrderApproval: false,
      enableOrderValidation: false,
      enablePaymentDocumentsB2B: false,
      enablePayments: false,
      enablePaymentsCollection: false,
      enablePriceOracle: false,
      enableSellerDiscount: true,
      enableTask: false,
      externalAccess: false,
      filterGroupedSuggestionsBy: [],
      "footerCustomContent.useFooterCustomContent": false,
      hasAllDistributionCenters: false,
      hasMultiUnitEnabled: true,
      hasMultipleBusinessUnit: false,
      hasNoSaleFilter: true,
      hasSingleDistributionCenter: true,
      hasStockEnabled: true,
      hasTransferPaymentType: false,
      hasTransportCode: false,
      hasVoucherPrinterEnabled: false,
      hidePrices: false,
      hideReceiptType: false,
      "hooks.cartShoppingHook": false,
      "hooks.getPendingDocumentsHook": false,
      "hooks.shippingHook": false,
      "hooks.stockHook": false,
      "hooks.updateTrafficLightHook": false,
      inMaintenance: false,
      includeTaxRateInPrices: true,
      lazyLoadingPrices: false,
      limitAddingByStock: true,
      ordersRequireAuthorization: false,
      ordersRequireVerification: false,
      "packaging.amountUsesUnits": true,
      "packagingInformation.hidePackagingInformationB2B": true,
      "packagingInformation.hideSingleItemPackagingInformationB2B": true,
      "packagingInformation.ignoreUnitOnPackInformationB2B": false,
      "payment.balances": [],
      "payment.enableNewPaymentModule": false,
      "payment.requiresFullPayment": false,
      paymentsWithoutAccount: false,
      pendingDocuments: false,
      pointsEnabled: false,
      priceRoundingDecimals: 0,
      "productDetailViewConfiguration.tabsOrder": ["steps", "description"],
      productVariability: "none",
      purchaseOrderEnabled: false,
      shareOrderNewDesign: false,
      "shoppingDetail.lastOrder": false,
      showEmptyCategories: false,
      showMinOne: false,
      "synchronization.backgroundSyncList": [],
      "synchronization.enableBackgroundSendOrders": false,
      "synchronization.enableBackgroundSync": false,
      "synchronization.enableSyncImages": false,
      "taxes.showSummary": true,
      "taxes.taxRate": 0,
      "taxes.useTaxRate": true,
      uploadOrderFileWithMinUnits: false,
      useMobileGps: false,
      useMongoPricing: false,
      useNewPromotions: true,
      validatePaymentFromAdmin: false,
      weightInfo: false,
    },
  },
};

export default clients;
