"""
sync-clients.py

Generates tests/e2e/fixtures/clients.ts from data/qa-matrix.json
Ensures clients.ts is always in sync with MongoDB via the extractor.

Usage:
    python3 tools/sync-clients.py

Workflow:
    1. python3 data/mongo-extractor.py   # MongoDB → qa-matrix.json
    2. python3 tools/sync-clients.py     # qa-matrix.json → clients.ts (AUTO-GENERATED)
    3. cd tests/e2e && npx playwright test
"""

import json
import sys
from pathlib import Path
from datetime import datetime, timezone


def load_qa_matrix(matrix_path: str = "data/qa-matrix.json") -> dict:
    """Load the qa-matrix.json file."""
    path = Path(matrix_path)
    if not path.exists():
        print(f"Error: {matrix_path} not found. Run: python3 data/mongo-extractor.py", file=sys.stderr)
        sys.exit(1)

    with open(path) as f:
        return json.load(f)


def map_domain_to_baseurl(domain: str) -> str:
    """Map MongoDB domain to frontend baseURL.

    yom.me = production
    solopide.me = staging
    """
    if ".youorder.me" in domain:
        return f"https://{domain}"
    elif ".solopide.me" in domain:
        return f"https://{domain}"
    else:
        return f"https://{domain}"


def format_conditional_tests(active_tests: dict) -> str:
    """Format conditional test list as comment."""
    if not active_tests.get("conditional"):
        return "// No conditional tests"
    tests = ", ".join(active_tests["conditional"][:10])
    if len(active_tests["conditional"]) > 10:
        tests += f", +{len(active_tests['conditional']) - 10} more"
    return f"// Conditional tests: {tests}"


def generate_clients_ts(qa_matrix: dict) -> str:
    """Generate TypeScript clients.ts from qa-matrix.json."""

    extracted_at = qa_matrix.get("extractedAt", datetime.now(timezone.utc).isoformat())

    header = f'''/**
 * AUTO-GENERATED by tools/sync-clients.py
 * Source: data/qa-matrix.json
 * Last sync: {extracted_at}
 *
 * DO NOT EDIT MANUALLY
 * To regenerate: python3 tools/sync-clients.py
 *
 * Flow:
 *   1. python3 data/mongo-extractor.py   # MongoDB → qa-matrix.json
 *   2. python3 tools/sync-clients.py     # qa-matrix.json → this file
 */

import {{ test as base, expect }} from '@playwright/test';

function creds(prefix: string) {{
  return {{
    email: process.env[`${{prefix}}_EMAIL`] || '',
    password: process.env[`${{prefix}}_PASSWORD`] || '',
  }};
}}

interface ClientConfig {{
  name: string;
  baseURL: string;
  loginPath: string;
  credentials: {{ email: string; password: string }};
  config: Record<string, any>;
  coupons?: Array<{{ code: string; discount: any }}>; // From yom-promotions
  banners?: Array<{{ title: string; position: string }}>; // From b2b-marketing
  promotions?: Array<any>; // From yom-promotions
}}

const clients: Record<string, ClientConfig> = {{
'''

    client_entries = []
    for client_key, client_data in qa_matrix.get("clients", {}).items():
        domain = client_data.get("domain", "")
        name = client_data.get("name", "")
        baseurl = map_domain_to_baseurl(domain)
        variables = client_data.get("variables", {})
        coupons = client_data.get("coupons", [])
        banners = client_data.get("banners", [])
        promotions = client_data.get("promotions", [])
        active_tests = client_data.get("activeTests", {})

        # Determine login path
        login_path = "/auth/jwt/login"
        if domain in ("codelpa.youorder.me", "beta-codelpa.solopide.me"):
            login_path = "/login"
        elif domain in ("soprole.youorder.me", "soprole.solopide.me"):
            login_path = "/login"

        # Format config object
        config_items = []
        for key, value in sorted(variables.items()):
            # Escape keys with dots (e.g., hooks.shippingHook → "hooks.shippingHook")
            key_str = f'"{key}"' if '.' in key else key
            if isinstance(value, bool):
                config_items.append(f"      {key_str}: {str(value).lower()},")
            elif isinstance(value, str):
                # Use json.dumps to properly escape strings (handles quotes, newlines, etc.)
                config_items.append(f"      {key_str}: {json.dumps(value)},")
            elif isinstance(value, (int, float)):
                config_items.append(f"      {key_str}: {value},")
            elif isinstance(value, list):
                config_items.append(f"      {key_str}: {json.dumps(value)},")
            elif isinstance(value, dict):
                config_items.append(f"      {key_str}: {json.dumps(value)},")
            else:
                config_items.append(f"      {key_str}: {value},")

        config_str = "\n".join(config_items)

        # Format coupons array for tests
        coupons_str = "[]"
        if coupons:
            coupon_items = [
                f'    {{ code: "{c.get("code", "")}", discount: {json.dumps(c.get("discount", {}))} }}'
                for c in coupons[:3]
            ]
            coupons_str = f"[\n{', '.join(coupon_items)}\n  ]"

        # Format banners array for tests
        banners_str = "[]"
        if banners:
            banner_items = [
                f'    {{ title: "{b.get("title", "")}", position: "{b.get("position", "")}" }}'
                for b in banners[:3]
            ]
            banners_str = f"[\n{', '.join(banner_items)}\n  ]"

        # Format promotions array
        promotions_str = "[]"
        if promotions:
            promotions_str = json.dumps(promotions[:5])

        # Conditional tests comment
        conditional_comment = format_conditional_tests(active_tests)

        # Quote client keys that have hyphens or start with numbers (invalid TS identifiers)
        client_key_str = f'"{client_key}"' if '-' in client_key or client_key[0].isdigit() else client_key

        entry = f'''  {client_key_str}: {{
    name: "{name}",
    baseURL: "{baseurl}",
    loginPath: "{login_path}",
    credentials: creds("{client_key.upper()}"),
    coupons: {coupons_str},
    banners: {banners_str},
    promotions: {promotions_str},
    {conditional_comment}
    config: {{
{config_str}
    }},
  }},
'''
        client_entries.append(entry)

    clients_section = "".join(client_entries)

    footer = '''};

export default clients;
'''

    return header + clients_section + footer


def main():
    """Main entry point."""
    print("Loading qa-matrix.json...")
    qa_matrix = load_qa_matrix()

    print(f"Generating clients.ts from {len(qa_matrix.get('clients', {}))} clients...")
    clients_ts = generate_clients_ts(qa_matrix)

    output_path = Path("tests/e2e/fixtures/clients.ts")
    output_path.write_text(clients_ts)

    print(f"✅ Generated {output_path}")
    print(f"   {len(qa_matrix.get('clients', {}))} clients")
    print(f"   Last sync: {qa_matrix.get('extractedAt', 'unknown')}")


if __name__ == "__main__":
    main()
